#!/bin/bash

# TODO find group for user

# TODO move home folder to
# /home/supervisor/users/<username>

echo "not finished"
exit 4

if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

if [ $# != 1 ]; then
    echo "Usage: ./remove <username>"
    exit 4
fi

