#!/bin/bash

if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

if [ $# != 1 ]; then
    echo "Usage:sudo ./sunset_user_reset_password <username>"
    exit 4
fi

USERNAME=$1
Xi=3
X=0
password=""

# Genereate random password
ALL_NON_RANDOM_WORDS=/usr/share/dict/words
non_random_words=`cat $ALL_NON_RANDOM_WORDS | wc -l`
while [ "$X" -lt "$Xi" ]
do
    random_number=`od -N3 -An -i /dev/urandom | awk -v f=0 -v r="$non_random_words" '{printf "%i\n", f + r * $1 / 16777216}'` 
    # sed `echo $random_number`"q;d" $ALL_NON_RANDOM_WORDS

    password=`sed $random_number"q;d" $ALL_NON_RANDOM_WORDS`$password

    let "X = X + 1"
done


# Print password
echo username: $USERNAME
echo password: $password

# Change the password
echo -e "$password\n$password" | passwd $USERNAME

# Forcing the users to change the password on next logon
# passwd --expire $USERNAME
chage -d 0 $USERNAME

