#!/usr/bin/env python

import sys
import re
from subprocess import Popen, PIPE

def shell(cmd, shell=False):

    if shell:
        p = Popen(cmd, shell=True, stdin=PIPE, stdout=PIPE, stderr=PIPE)
    else:
        cmd = cmd.split()
        p = Popen(cmd, stdin=PIPE, stdout=PIPE, stderr=PIPE)

    output, err = p.communicate()
    return output


if __name__ == "__main__":

    args = sys.argv[1:]

    # TODO do it for user
    # TODO do it for partition

    squeue = shell('squeue')

    for job in squeue.split('\n')[1:]:

        if job == "": continue

        job = job.split()[0]
        shell('scancel '+job)

